@echo off

set export DATABASE_URL=postgresql://postgres:omcms123@db.hbpovlzsgfmcyfcwrjzh.supabase.co:5432/postgres
set export SUPABASE_URL=https://hbpovlzsgfmcyfcwrjzh.supabase.co
set export SUPABASE_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhicG92bHpzZ2ZtY3lmY3dyanpoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MjUxMzAsImV4cCI6MjA1NzUwMTEzMH0.tQeMWQov2soOO6idfk57J4Fyaj98g777asAmcaRTkIY
set export SUPABASE_JWT_SECRET=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhicG92bHpzZ2ZtY3lmY3dyanpoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTkyNTEzMCwiZXhwIjoyMDU3NTAxMTMwfQ.R_3yzfV3CdjUwBfpghwhtp1MU-QAMKHTKHFwmsgOGsgsource .env.dev
